name: ✨ Feature request
description: Request a new feature to be added to DB UX Design System.
labels: ["🧑‍🧒‍🧒communityFeedback"]
type: Feature
projects: "db-ux-design-system/12"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue! Use this template if you want to request a new feature, or a change to an existing feature.
        If you are reporting a bug or problem, please use the bug template instead.
        
        📣 Please create a separate issue for each feature.
  
  - type: textarea
    id: description
    attributes:
      description: Give a clear and precise description of the new feature. If possible, be sure to include examples, screenshots or videos to illustrate your request.
      label: Description
      placeholder: 
    validations:
      required: true
